JJ = javac

Test : IConfig PanneauJeu FenetreJeu CarteTest PositionTest ElementTest clean

FenetreJeu :
	$(JJ) FenetreJeu.java

PanneauJeu:
	$(JJ) PanneauJeu.java

IConfig:
	$(JJ) IConfig.java
ElementTest :
	$(JJ) ElementTest.java
PositionTest:
	$(JJ) PositionTest.java
CarteTest:
	$(JJ) CarteTest.java

clean:
	rm -f *~
